export interface ReceiptData {
  id: string;
  trackingCode: string;
  transactionId: string;
  createdAt: string;
  updatedAt: string;

  // Parties
  senderName: string;
  receiverName: string;
  bankName: string;
  accountNumber: string;

  // Transaction
  amount: number;
  currency: string;
  status: "pending" | "processing" | "successful" | "failed" | "reversed";
  dateTime: string;
  paymentMethod: string;
  progress: number;
  feeAmount: number;
  feeStatus: "unresolved" | "pending" | "paid" | "waived";

  // Messaging
  billingWarning: string;
  pendingMessage: string;
  maturityMessage: string;
  customNotes: string;
  cryptoWallet: string;

  // Footer / Legal
  footerText: string;

  // Branding & Images
  backgroundColor: string;
  brandColor: string;
  logoUrl: string;
  bankLogoUrl: string;
  receiptImageUrl: string;

  // User association
  createdBy?: string;
  // Set for receipts generated while signed out, so the dashboard can tell
  // them apart from receipts that genuinely belong to the current user.
  isAnonymous?: boolean;
}

export interface ReceiptFormData {
  // Parties
  senderName: string;
  receiverName: string;
  bankName: string;
  accountNumber: string;

  // Transaction
  amount: string;
  currency: string;
  status: ReceiptData["status"];
  dateTime: string;
  paymentMethod: string;
  progress: string;
  feeAmount: string;
  feeStatus: ReceiptData["feeStatus"];

  // Messaging
  billingWarning: string;
  pendingMessage: string;
  maturityMessage: string;
  customNotes: string;
  cryptoWallet: string;

  // Footer / Legal
  footerText: string;

  // Branding & Images
  backgroundColor: string;
  brandColor: string;
  logoFile: File | null;
  bankLogoFile: File | null;
  receiptImageFile: File | null;

  // Generated fields (optional, for preview)
  trackingCode?: string;
  transactionId?: string;
}

export const defaultFormData: ReceiptFormData = {
  senderName: "",
  receiverName: "",
  bankName: "",
  accountNumber: "",
  amount: "",
  currency: "USD",
  status: "pending",
  dateTime: new Date().toISOString().slice(0, 16),
  paymentMethod: "Bank Transfer",
  progress: "0",
  feeAmount: "",
  feeStatus: "unresolved",
  billingWarning: "",
  pendingMessage: "We are processing your transfer.",
  maturityMessage: "We apologize for any inconvenience. Thank you for selecting our bank for your financial needs.",
  customNotes: "",
  cryptoWallet: "",
  // Placeholder legal copy for a demo project. Replace with your organisation's
// real, verified details before using this anywhere customer-facing. Do not
// publish regulatory claims (licences, registration numbers, regulators) unless
// they are accurate.
  footerText: "DEMO RECEIPT — NOT A REAL PAYMENT CONFIRMATION. This receipt was generated by a demonstration application to illustrate a transfer-tracking interface. No money has been transferred, no funds are held, and no payment service is provided.\n\nCertiPay is a fictional brand created for this demo. Any regulatory status, licence number, registered address, or company registration shown anywhere in this project is placeholder text and must be replaced with accurate, verified information before any real use.\n\nCopyright 2025 CertiPay (demo project)",
  backgroundColor: "#f8fafc",
  brandColor: "#1e40af",
  logoFile: null,
  bankLogoFile: null,
  receiptImageFile: null,
};

export const CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD", "JPY", "CHF", "CNY", "INR", "BRL"];
export const PAYMENT_METHODS = ["Bank Transfer", "Wire Transfer", "ACH", "SWIFT", "SEPA", "Crypto", "Card", "Cash"];
export const STATUSES = ["pending", "processing", "successful", "failed", "reversed"] as const;
export const FEE_STATUSES = ["unresolved", "pending", "paid", "waived"] as const;